/**
 * Test-Script für die automatische Keyword-Generierung
 *
 * Dieses Script zeigt die Unterschiede zwischen manuellen und
 * automatisch generierten Keywords und deren Qualität.
 */

import { articles, categories, keywords, autoGeneratedKeywords, compareKeywords } from '../data/mockData';

console.log('=====================================');
console.log('🔍 KEYWORD GENERIERUNG - TEST REPORT');
console.log('=====================================\n');

// 1. Basis-Statistiken
console.log('📊 BASIS-STATISTIKEN');
console.log('─────────────────────');
console.log(`Anzahl Artikel: ${articles.length}`);
console.log(`Anzahl Kategorien: ${categories.length}`);
console.log(`Manuelle Keywords: ${keywords.length}`);
console.log(`Generierte Keywords: ${autoGeneratedKeywords.length}\n`);

// 2. Top 10 Generierte Keywords
console.log('🏆 TOP 10 GENERIERTE KEYWORDS');
console.log('─────────────────────────────');
autoGeneratedKeywords
  .slice(0, 10)
  .forEach((kw, index) => {
    console.log(`${index + 1}. ${kw.text.padEnd(30)} | Score: ${kw.value}/100 | Kategorie: ${kw.category} | Artikel: ${kw.articles.length}`);
  });
console.log('');

// 3. Vergleich
console.log('🔄 VERGLEICH: MANUELL vs. GENERIERT');
console.log('────────────────────────────────────');
const comparison = compareKeywords();
console.log(`Nur in manuell: ${comparison.onlyInManual.length} Keywords`);
console.log(`Nur in generiert: ${comparison.onlyInGenerated.length} Keywords`);
console.log(`In beiden: ${comparison.inBoth.length} Keywords\n`);

// 4. Beispiele für neue entdeckte Keywords
console.log('✨ NEU ENTDECKTE KEYWORDS (nur in generiert)');
console.log('─────────────────────────────────────────────');
comparison.onlyInGenerated.slice(0, 15).forEach((kw, index) => {
  const kwData = autoGeneratedKeywords.find(k => k.text === kw);
  if (kwData) {
    console.log(`${index + 1}. ${kw.padEnd(30)} | Score: ${kwData.value}/100`);
  }
});
console.log('');

// 5. Kategorien-Verteilung
console.log('📂 KATEGORIEN-VERTEILUNG (generierte Keywords)');
console.log('────────────────────────────────────────────');
const categoryDistribution: Record<string, number> = {};
autoGeneratedKeywords.forEach(kw => {
  categoryDistribution[kw.category] = (categoryDistribution[kw.category] || 0) + 1;
});

Object.entries(categoryDistribution)
  .sort((a, b) => b[1] - a[1])
  .slice(0, 10)
  .forEach(([category, count]) => {
    const categoryName = categories.find(c => c.id === category)?.name || category;
    console.log(`${categoryName.padEnd(35)} | ${count} Keywords`);
  });
console.log('');

// 6. Geografische Abdeckung
console.log('🌍 GEOGRAFISCHE ABDECKUNG (generierte Keywords)');
console.log('─────────────────────────────────────────────');
const continentCoverage: Record<string, number> = {};
autoGeneratedKeywords.forEach(kw => {
  kw.continents.forEach(continent => {
    continentCoverage[continent] = (continentCoverage[continent] || 0) + 1;
  });
});

Object.entries(continentCoverage)
  .sort((a, b) => b[1] - a[1])
  .forEach(([continent, count]) => {
    console.log(`${continent.padEnd(20)} | ${count} Keywords`);
  });
console.log('');

// 7. Qualitäts-Metriken
console.log('📈 QUALITÄTS-METRIKEN');
console.log('─────────────────────');
const avgScore = autoGeneratedKeywords.reduce((sum, kw) => sum + kw.value, 0) / autoGeneratedKeywords.length;
const avgArticlesPerKeyword = autoGeneratedKeywords.reduce((sum, kw) => sum + kw.articles.length, 0) / autoGeneratedKeywords.length;
const avgRegionsPerKeyword = autoGeneratedKeywords.reduce((sum, kw) => sum + kw.regions.length, 0) / autoGeneratedKeywords.length;

console.log(`Durchschnittlicher Score: ${avgScore.toFixed(2)}/100`);
console.log(`Durchschnitt Artikel pro Keyword: ${avgArticlesPerKeyword.toFixed(2)}`);
console.log(`Durchschnitt Regionen pro Keyword: ${avgRegionsPerKeyword.toFixed(2)}`);
console.log('');

// 8. Beispiel-Keywords mit Details
console.log('🔬 DETAILLIERTE BEISPIELE');
console.log('─────────────────────────');
autoGeneratedKeywords.slice(0, 3).forEach((kw, index) => {
  console.log(`\n${index + 1}. ${kw.text}`);
  console.log(`   Score: ${kw.value}/100`);
  console.log(`   Kategorie: ${kw.category}`);
  console.log(`   Kontinente: ${kw.continents.join(', ')}`);
  console.log(`   Regionen: ${kw.regions.join(', ')}`);
  console.log(`   Anzahl Artikel: ${kw.articles.length}`);
});
console.log('');

console.log('=====================================');
console.log('✅ TEST ABGESCHLOSSEN');
console.log('=====================================');

export { comparison, categoryDistribution, continentCoverage };
